# Generated by Django 5.2.17 on 2026-09-18 11:00

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.image_path, validators=[apps.core.uploads.validate_image]),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Use +998 followed by 9 digits.')])),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=300)),
                ('landmark', models.CharField(blank=True, max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user')],
            },
        ),
    ]
