# Generated by Django 5.2.17 on 2026-09-18 11:06

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='TrendBox', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to=apps.core.uploads.image_path, validators=[apps.core.uploads.validate_image])),
                ('landing_uz', models.TextField(blank=True)),
                ('landing_ru', models.TextField(blank=True)),
                ('landing_en', models.TextField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=25000, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_low_stock_threshold', models.PositiveIntegerField(default=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='store_singleton'), models.CheckConstraint(condition=models.Q(('shipping_fee__gte', 0)), name='shipping_nonnegative')],
            },
        ),
    ]
