"""Original demo catalog. These product illustrations are generated locally."""
CATEGORIES = [
    ('gadgets', 'Gadjetlar', 'Гаджеты', 'Gadgets'),
    ('home', 'Uy uchun', 'Для дома', 'Home essentials'),
    ('kitchen', 'Oshxona', 'Кухня', 'Kitchen'),
    ('phone', 'Telefon aksessuarlari', 'Аксессуары для телефона', 'Phone accessories'),
    ('car', 'Avtomobil uchun', 'Для автомобиля', 'Car accessories'),
    ('travel', 'Sayohat', 'Путешествия', 'Travel'),
]
PRODUCTS = [
    ('desk-lamp', 0, 'Sensorli stol chirog‘i', 'Сенсорная настольная лампа', 'Touch desk lamp', 189000, 'lamp'),
    ('mini-fan', 0, 'Ixcham stol ventilyatori', 'Компактный настольный вентилятор', 'Compact desk fan', 129000, 'fan'),
    ('digital-clock', 0, 'Raqamli stol soati', 'Цифровые настольные часы', 'Digital desk clock', 149000, 'clock'),
    ('cable-organizer', 0, 'Kabel tartiblagich to‘plami', 'Набор держателей кабеля', 'Cable organizer set', 39000, 'organizer'),
    ('storage-box', 1, 'Qopqoqli saqlash qutisi', 'Контейнер с крышкой', 'Lidded storage box', 89000, 'box'),
    ('wall-hooks', 1, 'Yopishqoq ilgaklar to‘plami', 'Набор самоклеящихся крючков', 'Adhesive hook set', 35000, 'organizer'),
    ('night-light', 1, 'Yumshoq nurli tungi chiroq', 'Ночник с мягким светом', 'Soft glow night light', 119000, 'lamp'),
    ('desk-tray', 1, 'Stol uchun tartiblagich', 'Органайзер для стола', 'Desktop organizer tray', 69000, 'box'),
    ('oil-sprayer', 2, 'Yog‘ purkagich idishi', 'Распылитель для масла', 'Kitchen oil sprayer', 59000, 'bottle'),
    ('kitchen-scale', 2, 'Elektron oshxona tarozisi', 'Электронные кухонные весы', 'Digital kitchen scale', 109000, 'clock'),
    ('silicone-tools', 2, 'Silikon oshxona anjomlari', 'Силиконные кухонные принадлежности', 'Silicone kitchen tools', 99000, 'tools'),
    ('lunch-box', 2, 'Bo‘limli tushlik qutisi', 'Ланч-бокс с отделениями', 'Divided lunch box', 79000, 'box'),
    ('phone-stand', 3, 'Buklanadigan telefon tagligi', 'Складная подставка для телефона', 'Folding phone stand', 49000, 'stand'),
    ('usb-c-cable', 3, 'USB-C quvvat kabeli', 'Кабель питания USB-C', 'USB-C charging cable', 45000, 'cable'),
    ('phone-pouch', 3, 'Telefon uchun himoya g‘ilofi', 'Защитный чехол для телефона', 'Protective phone pouch', 55000, 'phone'),
    ('charger', 3, 'Ikki portli quvvat adapteri', 'Зарядное устройство с двумя портами', 'Dual port wall charger', 139000, 'charger'),
    ('car-holder', 4, 'Avtomobil telefon tutqichi', 'Автомобильный держатель телефона', 'Car phone mount', 89000, 'stand'),
    ('car-organizer', 4, 'O‘rindiq uchun tartiblagich', 'Органайзер для сиденья', 'Car seat organizer', 119000, 'box'),
    ('car-charger', 4, 'Avtomobil quvvat adapteri', 'Автомобильное зарядное устройство', 'Car charging adapter', 99000, 'charger'),
    ('cleaning-kit', 4, 'Avtomobil tozalash to‘plami', 'Набор для чистки автомобиля', 'Car cleaning kit', 75000, 'tools'),
    ('travel-bottle', 5, 'Sayohat suv idishi', 'Дорожная бутылка для воды', 'Travel water bottle', 89000, 'bottle'),
    ('packing-cubes', 5, 'Chamadon tartiblagichlari', 'Органайзеры для чемодана', 'Packing cube set', 129000, 'box'),
    ('travel-pillow', 5, 'Sayohat bo‘yin yostiqchasi', 'Дорожная подушка для шеи', 'Travel neck pillow', 79000, 'pillow'),
    ('luggage-tag', 5, 'Chamadon belgilari to‘plami', 'Набор багажных бирок', 'Luggage tag set', 29000, 'phone'),
]
DETAILS = {
    'lamp': ('Yorug‘likni bir tegish bilan boshqaring. Stol yonida ixcham joy egallaydi.', 'Управляйте светом одним касанием. Компактный корпус занимает мало места.', 'Control the light with a touch. A compact body fits neatly beside your workspace.'),
    'fan': ('Stol uchun yengil va ko‘chirishga qulay ventilyator.', 'Лёгкий вентилятор для стола, который удобно переносить.', 'A lightweight desk fan that is easy to move between rooms.'),
    'clock': ('Aniq raqamli ekran natijani tez o‘qish imkonini beradi.', 'Чёткий цифровой экран позволяет быстро прочитать показания.', 'A clear digital display makes readings easy to see at a glance.'),
    'organizer': ('Mayda buyumlarni bir joyda saqlang. Silliq yuzaga o‘rnatish qulay.', 'Храните мелочи вместе. Легко разместить на гладкой поверхности.', 'Keep small essentials together. Easy to position on a smooth surface.'),
    'box': ('Buyumlarni tartibli saqlash uchun yengil va mustahkam quti.', 'Лёгкий прочный контейнер для аккуратного хранения вещей.', 'A lightweight, sturdy container to keep everyday items organized.'),
    'bottle': ('Qayta to‘ldiriladigan idish. Ishlatgandan so‘ng qo‘lda yuvish tavsiya etiladi.', 'Многоразовая ёмкость. После использования рекомендуется ручная мойка.', 'A refillable container. Hand washing after use is recommended.'),
    'tools': ('Kundalik ishlar uchun qulay to‘plam. Ishlatgandan keyin tozalab quriting.', 'Удобный набор на каждый день. Очистите и высушите после использования.', 'A practical set for everyday tasks. Clean and dry after use.'),
    'stand': ('Qurilmani ko‘rinadigan holatda ushlab turadi. O‘rnatishdan oldin mosligini tekshiring.', 'Удерживает устройство в поле зрения. Проверьте совместимость перед установкой.', 'Keeps your device in view. Check compatibility before fitting.'),
    'cable': ('USB-C qurilmalarini ulash uchun kundalik kabel. Ulagich turini tekshiring.', 'Повседневный кабель для устройств USB-C. Проверьте тип разъёма.', 'An everyday cable for USB-C devices. Check your connector type.'),
    'phone': ('Yengil himoya aksessuari. Xarid qilishdan oldin o‘lcham mosligini tekshiring.', 'Лёгкий защитный аксессуар. Проверьте размеры перед покупкой.', 'A lightweight protective accessory. Check dimensions before ordering.'),
    'charger': ('Mos qurilmalarni quvvatlash uchun adapter. Qurilma talablariga mos kabel ishlating.', 'Адаптер для совместимых устройств. Используйте подходящий кабель.', 'An adapter for compatible devices. Use a cable suited to your device.'),
    'pillow': ('Safarda bo‘yinni qulay tutish uchun yumshoq yostiqcha.', 'Мягкая подушка для удобного положения шеи в дороге.', 'A soft pillow to support a comfortable neck position while travelling.'),
}

