# Generated by Django 5.2.17 on 2026-09-18 10:57

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=180)),
                ('name_ru', models.CharField(blank=True, max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.core.uploads.image_path, validators=[apps.core.uploads.validate_image])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=180)),
                ('name_ru', models.CharField(blank=True, max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('short_description_uz', models.CharField(blank=True, max_length=300)),
                ('short_description_ru', models.CharField(blank=True, max_length=300)),
                ('short_description_en', models.CharField(blank=True, max_length=300)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.uploads.image_path, validators=[apps.core.uploads.validate_image])),
                ('alt_uz', models.CharField(blank=True, max_length=180)),
                ('alt_ru', models.CharField(blank=True, max_length=180)),
                ('alt_en', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_product_image')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('canonical_attribute_key', models.CharField(default='{}', editable=False, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.core.uploads.image_path, validators=[apps.core.uploads.validate_image])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'canonical_attribute_key'), name='unique_product_attributes'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='variant_positive_price'), models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('price')), _connector='OR'), name='variant_compare_price')],
            },
        ),
    ]
